name: Container
on: pull_request

jobs:
  node_container:
    runs-on: ubuntu-latest
    container: node:14.16.0-alpine3.13
    steps:
      - name: Log node version
        run: |
          node -v
          cat /etc/os-release
