name: matrix
on: push

jobs:
  node-version: 
    runs-on: ubuntu-20.04
    steps:
      - name: Log node version
        run: node -v
      - uses: actions/setup-node@v2
        with:
          node-version: '6'
      - name: Log node version
        run: node -v